[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
testpaths = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py310"
required-version = "0.16.0"
force-exclude = true
extend-include = ["*.ipynb"]

[tool.ruff.format]
preview = true
docstring-code-format = true

[tool.ruff.lint]
preview = true
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
select = [
  "E", "F", "W", # flake8
  "B",           # flake8-bugbear
  "I",           # isort
  "ARG",         # flake8-unused-arguments
  "C4",          # flake8-comprehensions
  "EM",          # flake8-errmsg
  "ICN",         # flake8-import-conventions
  "G",           # flake8-logging-format
  "PGH",         # pygrep-hooks
  "PIE",         # flake8-pie
  "PL",          # pylint
  "PTH",         # flake8-use-pathlib
  "RET",         # flake8-return
  "RUF",         # Ruff-specific
  "S",           # flake8-bandit
  "SIM",         # flake8-simplify
  "T20",         # flake8-print
  "UP",          # pyupgrade
  "YTT",         # flake8-2020
  "EXE",         # flake8-executable
]
ignore = [
  "function-call-in-default-argument",  # Function calls in default arguments
  "useless-expression",       # Useless expressions
  "pytest-raises-ambiguous-pattern", 
  "PLR",                      # Design related pylint codes
  "raw-string-in-exception",  # Exception must not use a string literal, assign to variable first
  "f-string-in-exception",    # Exception must not use an f-string literal, assign to variable first
  "unused-method-argument",   # Unused method argument:
  "assert",                   # Use of `assert` detected
  "mutable-class-default",    # Mutable class attributes should be annotated with `typing.ClassVar`
  "redefined-loop-name",      # `for` loop variable `value` overwritten by assignment target
]

[tool.ruff.lint.flake8-pytest-style]
mark-parentheses = false
fixture-parentheses = false
raises-require-match-for = ["*"]
warns-require-match-for = ["*"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.isort]
known-first-party = ["mlflow_mongodb"]

[tool.ruff.lint.flake8-tidy-imports.banned-api]
"pkg_resources".msg = "Do not use pkg_resources. Use importlib.resources or importlib.metadata instead."
"entrypoints".msg = "Do not use entrypoints. Use importlib.metadata.entry_points instead."
"pip".msg = "Importing pip can cause undesired side effects."

[tool.ruff.lint.per-file-ignores]
"mlflow_mongodb/model_registry_store.py" = ["import-private-name"]

[tool.ruff.lint.pydocstyle]
convention = "google"
